/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-12-03 20:10:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uni.member.model.vo.Member;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/about/../common/footer.jsp", Long.valueOf(1669752492866L));
    _jspx_dependants.put("/views/about/../common/menubar.jsp", Long.valueOf(1669926799245L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uni.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>about</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"<c:url value=\"/resources/user/css/boostrap.min.css\"/>\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"<c:url value=\"/resources/user/js/boostrap.min,js\"/>\"></script> \r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("*, *:before, *:after {\r\n");
      out.write("  box-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 33.3%;\r\n");
      out.write("  margin-bottom: 16px;\r\n");
      out.write("  padding: 0 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("  margin: 8px;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .ine:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: BlueViolet;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .jing:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: yellow;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .lilpa:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: Indigo;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .jururu:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: pink;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .gosegu:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color:lightblue;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column .vichan:hover{\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("  background-color: lightgreen;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".about-section {\r\n");
      out.write("  padding: 50px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: rgb(250, 142, 174);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  padding: 0 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container::after, .row::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  clear: both;\r\n");
      out.write("  display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("  color:rgb(250, 142, 174);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  border: none;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  background-color: rgb(250, 142, 174);\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border-radius:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {\r\n");
      out.write("  background-color: rgb(210, 57, 103);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String msg = (String)session.getAttribute("msg");
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		background:url('");
      out.print(request.getContextPath() );
      out.write("/resources/images/2.jpg') no-repeat; \r\n");
      out.write("		background-position: 50% 50%;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-size: 50% 50%;\r\n");
      out.write("		background-color: black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#loginForm, #userInfo{float:right;}\r\n");
      out.write("	.btns button{border: 1px solid skyblue;\r\n");
      out.write("            background-color: rgba(0,0,0,0);\r\n");
      out.write("            color: skyblue;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("				  }\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#enrollBtn, #mypageBtn{\r\n");
      out.write("			border-top-right-radius: 5px;\r\n");
      out.write("            border-bottom-right-radius: 5px;    \r\n");
      out.write("            margin-left:-3px}\r\n");
      out.write("	#loginBtn, #logoutBtn{ \r\n");
      out.write("			border-top-left-radius: 5px;\r\n");
      out.write("            border-bottom-left-radius: 5px;\r\n");
      out.write("            margin-right:-4px;}\r\n");
      out.write("	#userInfo a{text-decoration:none;color:white;}\r\n");
      out.write("	\r\n");
      out.write("	.btns button:hover{border: 1px solid skyblue;\r\n");
      out.write("            background-color: skyblue;\r\n");
      out.write("            color: purple;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("				  }\r\n");
      out.write("	\r\n");
      out.write("	/* 메뉴영역 관련 스타일*/\r\n");
      out.write("	.navWrap{background-color:black; width:100%; height:50px}\r\n");
      out.write("	.navWrap>.nav{width:600px;margin:auto;}\r\n");
      out.write("	.menu{text-align:center;color:white;font-weight:bold;width:150px;height:50px;display:table-cell;font-size:20px;vertical-align:middle;}\r\n");
      out.write("	.menu:hover{background-color:rgb(250, 142, 174); text-shadow:5px 5px 5px rgb(0,0,0);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	.logo{\r\n");
      out.write("		float: lfet;\r\n");
      out.write("	}\r\n");
      out.write("	.logo img{\r\n");
      out.write("		height: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function loginValidate(){\r\n");
      out.write("		if($(\"#userId\").val().trim().length === 0){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#userPwd\").val().trim().length === 0){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 class=\"logo\">\r\n");
      out.write("		<img src=\"resources/images/logo.png\" alt=\"로고\" >\r\n");
      out.write("	</h1>\r\n");
      out.write("	<h1 align=\"center\" style=\"color:white;\">이세계 아이돌</h1>\r\n");
      out.write("	<div class=\"loginArea\">\r\n");
      out.write("	");
 if( loginUser == null) { 
      out.write("\r\n");
      out.write("	<form id = \"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/loginMember.do\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th><label for = \"userId\" style=\"color:white;\">아이디</label></th>\r\n");
      out.write("					<td><input id=\"userId\" type=\"text\" name=\"userId\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th><label for = \"userPwd\" style=\"color:white;\">비밀번호</label></th>\r\n");
      out.write("					<td><input type=\"password\" id=\"userPwd\" type=\"text\" name=\"userPwd\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class =\"btns\" align=\"center\">\r\n");
      out.write("				\r\n");
      out.write("				<button id = \"loginBtn\" type=\"submit\">로그인</button>\r\n");
      out.write("			    <button id = \"enrollBtn\" type=\"button\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("	");
} else{ 
      out.write("\r\n");
      out.write("			<div id = \"userInfo\">\r\n");
      out.write("				<b style = \"color:white;\">");
      out.print(loginUser.getUserName() );
      out.write(" 님 </b> 의 방문을 환영합니다.\r\n");
      out.write("				<br><br>\r\n");
      out.write("				<div class =\"btns\" align=\"center\">\r\n");
      out.write("					<a href = \"");
      out.print(request.getContextPath() );
      out.write("/mypageMember.do\">마이페이지</a>\r\n");
      out.write("					<a href = \"");
      out.print(request.getContextPath() );
      out.write("/logoutMember.do\">로그아웃</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</div>	\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function enrollPage(){\r\n");
      out.write("			location.href =\"");
      out.print(request.getContextPath());
      out.write("/enrollFormMember.do\";\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<br clear=\"both\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<div class=\"menu\" onclick=\"goMain();\">HOME</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goAbout();\">ABOUT</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goNotice();\">공지사항</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goBoard();\">게시판</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goThumbnail();\">사진게시판</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("		function goMain(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function goAbout(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("/about.do\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function goNotice(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("/listNotice.do\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"about-section\">\r\n");
      out.write("  <h1>이세돌 맴버</h1>\r\n");
      out.write("  <p>이세계 아이돌은 트위치 스트리머 우왁굳이 기획한 프로젝트[9]를 통해 만들어진 6인조 버츄얼 걸그룹[10]으로, 2021년 12월 17일 디지털 싱글 앨범 RE : WIND를 발매하여 정식으로 데뷔하였다.</p>\r\n");
      out.write("  <p>1집 RE:WIND | 2집 겨울봄 | 3집 예정 | 4집 예정</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2 style=\"text-align:center\">이세돌 프로필</h2>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"ine\" src=\"resources/images/ine.png\" alt=\"아이네\" onclick=\"goIne();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>아이네</h2>\r\n");
      out.write("        <p class=\"title\">메인보컬</p>\r\n");
      out.write("        <p>출색:1994년 키:158cm 혈액형:B형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/channel/UCroM00J2ahCN6k-0-oAiDxg\"><p><button class=\"button\">아이네 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/vo_ine\"><p><button class=\"button\">아이네 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"jing\" src=\"resources/images/jing.png\" alt=\"징버거\" onclick=\"goJing();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>징버거</h2>\r\n");
      out.write("        <p class=\"title\">서브보컬</p>\r\n");
      out.write("         <p>출색:1995년10월08일 키:61.9cm 혈액형:B형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/c/%EC%A7%95%EB%B2%84%EA%B1%B0\"><p><button class=\"button\">징버거 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/jingburger\"><p><button class=\"button\">징버거 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"lilpa\" src=\"resources/images/lilpa.png\" alt=\"릴파\" onclick=\"goLilpa();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>릴파</h2>\r\n");
      out.write("        <p class=\"title\">메인보컬</p>\r\n");
      out.write("        <p>출색:1996년03월09일 키:164cm 혈액형:O형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/channel/UC-oCJP9t47v7-DmsnmXV38Q\"><p><button class=\"button\">릴파 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/lilpaaaaaa\"><p><button class=\"button\">릴파 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"jururu\" src=\"resources/images/jururu.png\" alt=\"주르르\" onclick=\"goJururu();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>주르르</h2>\r\n");
      out.write("       <p class=\"title\">서브보컬</p>\r\n");
      out.write("        <p>출색:1997년06월10일 키:161.9cm 혈액형:O형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/channel/UCTifMx1ONpElK5x6B4ng8eg/featured\"><p><button class=\"button\">주르르 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/cotton__123\"><p><button class=\"button\">주르르 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"gosegu\" src=\"resources/images/gosegu.png\" alt=\"고세구\" onclick=\"goGosegu();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>고세구</h2>\r\n");
      out.write("       <p class=\"title\">래퍼</p>\r\n");
      out.write("        <p>출색:1998년 키:300m 혈액형:B형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/channel/UCV9WL7sW6_KjanYkUUaIDfQ\"><p><button class=\"button\">고세구 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/gosegugosegu\"><p><button class=\"button\">고세구 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <img class=\"vichan\" src=\"resources/images/vichan.png\" alt=\"비챤\" onclick=\"goVichan();\" style=\"width:100%\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>비챤</h2>\r\n");
      out.write("        <p class=\"title\">리드보컬</p>\r\n");
      out.write("        <p>출색:2000년01월16일 키:160cm 혈액형:B형</p>\r\n");
      out.write("        <a href=\"https://www.youtube.com/channel/UCs6EwgxKLY9GG4QNUrP5hoQ\"><p><button class=\"button\">비챤 유튜브</button></p></a>\r\n");
      out.write("        <a href=\"https://www.twitch.tv/viichan6\"><p><button class=\"button\">비챤 트위치</button></p></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			function goIne(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/Ine.do\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function goJing(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/Jing.do\";\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			function goLilpa(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/lilpa.do\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function goJururu(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/Jururu.do\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			function goGosegu(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/Gosegu.do\";\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			function goVichan(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("/Vichan.do\";\r\n");
      out.write("			}\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* div{border:1px solid red;} */\r\n");
      out.write("    #footer{\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer>div{\r\n");
      out.write("    	width:100%;\r\n");
      out.write("    	padding-left:10%;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1{\r\n");
      out.write("        height:20%;\r\n");
      out.write("        border-top:1px solid lightgray;\r\n");
      out.write("        border-bottom:1px solid lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2{\r\n");
      out.write("        height:80%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer-1 > a{\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin:10px;\r\n");
      out.write("        line-height: 40px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2>p{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("    #p1{\r\n");
      out.write("    	color:white;\r\n");
      out.write("    }\r\n");
      out.write("    #p2{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("	a:link{\r\n");
      out.write("		color:royalblue;\r\n");
      out.write("	    transition : 1s; /* 속성 변경할 때 효과의 속도 조절 */\r\n");
      out.write("	}\r\n");
      out.write("	a:visited {\r\n");
      out.write("		color:teal;\r\n");
      out.write("	}\r\n");
      out.write("	a:hover {\r\n");
      out.write("		color:purple;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	a:active{\r\n");
      out.write("		color:blue;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		text-decoration: none;	\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("        <div id=\"footer-1\">\r\n");
      out.write("            <a href=\"https://woowakgood.com/\">왁물원</a> | \r\n");
      out.write("            <a href=\"https://www.youtube.com/c/welshcorgimessi\">왁타버스</a> | \r\n");
      out.write("            <a href=\"https://github.com/ChoiYoonJong\">제작자:초이</a>  \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer-2\">\r\n");
      out.write("            <p id=\"p1\">\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCroM00J2ahCN6k-0-oAiDxg\">아이네</a> : 1994년|158cm|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/c/%EC%A7%95%EB%B2%84%EA%B1%B0\">징버거</a> : 1995년10월08일|161.9cm|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UC-oCJP9t47v7-DmsnmXV38Q\">릴파</a> : 1996년03월09일|164cm|O형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/c/%EC%A3%BC%EB%A5%B4%EB%A5%B4\">주르르</a> : 1997년06월10일|161.9cm|O형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCV9WL7sW6_KjanYkUUaIDfQ\">고세구</a> : 1998년|300m|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCs6EwgxKLY9GG4QNUrP5hoQ\">비챤</a> : 2000년01월16일|160cm|B형 \r\n");
      out.write("                \r\n");
      out.write("            </p>  \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
