/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-12-03 22:56:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.iseprofile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lilpa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("	margin:0;\r\n");
      out.write("	padding:0;\r\n");
      out.write("	box-sizing:border-box;\r\n");
      out.write("	font-family:'Poppins',sans-serif;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:100vh;\r\n");
      out.write("	background-image:linear-gradient(rgba(12,3,51,0.3),rgba(12,3,51,0.3));\r\n");
      out.write("	padding:0 5%;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	align-items:center;\r\n");
      out.write("	justify-content:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(":root{\r\n");
      out.write("	--backgroung-color:#fff;\r\n");
      out.write("	--text-color:#555;\r\n");
      out.write("	--title-color:#000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("	background:var(--background-color);\r\n");
      out.write("	color:var(--text-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("nav{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	top:0;\r\n");
      out.write("	left:0;\r\n");
      out.write("	padding:20px 8%;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	align-items:center;\r\n");
      out.write("	justify-content:space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*로고,메뉴창 디자인 정리*/\r\n");
      out.write("nav .logo{\r\n");
      out.write("	width:250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li{\r\n");
      out.write("	list-style:none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-left:40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a{\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	color:white;\r\n");
      out.write("	font-size:17px;\r\n");
      out.write("}\r\n");
      out.write("nav ul li a:hover{\r\n");
      out.write("	text-decoration:none;\r\n");
      out.write("	color:Indigo;\r\n");
      out.write("	font-weight:bold;\r\n");
      out.write("	text-shadow: #FC0 1px 0 10px;\r\n");
      out.write("	font-size:17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*릴파 소개글 디자인 */\r\n");
      out.write(".pcontent{\r\n");
      out.write("	margin-top:110%;\r\n");
      out.write("	max-width:700%;\r\n");
      out.write("	margin-left:50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pcontent h1{\r\n");
      out.write("	font-size:70px;\r\n");
      out.write("	font-family:serif;\r\n");
      out.write("	color:var(--title-color);\r\n");
      out.write("	font-weight:500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pcontent h1 span{\r\n");
      out.write("	font-family:serif;\r\n");
      out.write("	font-weight:1000;\r\n");
      out.write("	color:Indigo;\r\n");
      out.write("	font-style:Amarillo;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pcontent p span{\r\n");
      out.write("	font-family:serif;\r\n");
      out.write("	font-weight:1000;\r\n");
      out.write("	color:Indigo;\r\n");
      out.write("	font-style:Amarillo;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*릴파 소개 이미지 디자인 */\r\n");
      out.write(".image-box img{\r\n");
      out.write("	width:1000px;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-box {\r\n");
      out.write("	width:100px;\r\n");
      out.write("	height:100%;\r\n");
      out.write("	right:40%;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*릴파 맨위 자동 영상 디자인 및 위치 */\r\n");
      out.write(".videocontent{\r\n");
      out.write("	text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".back-video{\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	right:0;\r\n");
      out.write("	bottom:0;\r\n");
      out.write("	z-index:-1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(min-aspect-ratio: 16/9){\r\n");
      out.write("	.back-video{\r\n");
      out.write("		width:120%;\r\n");
      out.write("		height:auto;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("@media(max-aspect-ratio: 16/9){\r\n");
      out.write("	.back-video{\r\n");
      out.write("		width:auto;\r\n");
      out.write("		height:100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("	\r\n");
      out.write("		<video autoplay loop muted plays-inline class=\"back-video\">\r\n");
      out.write("			<source src=\"resources/videos/lilpaintro.mp4\" type=\"video/mp4\">\r\n");
      out.write("		</video>\r\n");
      out.write("		\r\n");
      out.write("		<nav>\r\n");
      out.write("			<img src=\"resources/images/isedol.png\" class=\"logo\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#\" onclick=\"goMain();\">HOME</a></li>\r\n");
      out.write("				<li><a href=\"#\">ANOTHER</a></li>\r\n");
      out.write("				<li><a href=\"#\">MUSICVIDEOS</a></li>\r\n");
      out.write("				<li><a href=\"https://www.twitch.tv/lilpaaaaaa\">TWITCH</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div class=\"videocontent\">\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"pcontent\">\r\n");
      out.write("				\r\n");
      out.write("				<h1>안녕하세요 저는 <span>릴파</span>에요!</h1>\r\n");
      out.write("				<br><br>\r\n");
      out.write("				<p>전직 아이돌 출신 이자 노력의 아이콘으로 불리며 이세계 아이돌 활동으로 떡상하게 된<span>'릴파'</span>는\r\n");
      out.write("				<span>1996년3월9일</span>생으로 올해 나이 <span>27세</span>입니다. 키는 164cm MBTI ENFP로 인싸의 기질이 충만한 그녀는\r\n");
      out.write("				고등학생 시절에는 여자애들끼리 같이 급식을 먹는데 계속 말하느라 항상 밥이 남을 정도였다고 합니다.\r\n");
      out.write("				방과 후 활동은 노래 부르는 동아리에 가입했고 대학교 학과는 실용음악 재즈보털 전공을 했다고합니다.\r\n");
      out.write("				릴파는 '이세계아이돌'에서 유일한 전직 아이돌 경력을 가진 멤버입니다. 연습생 시절 164cm 43kg까지\r\n");
      out.write("				감량을 했던 릴파는 무리한 다이어트와연습으로 열걸음 걸으면 쓰러질 정도였다고한다.이후 무대에 설 기회를\r\n");
      out.write("				얻어 메인보컬로 데뷔하게 됩니다.하지만 활동한지 1년만에 한 대학축제 마지막으로 아이돌 그룹이 해체됩니다.\r\n");
      out.write("				아이돌 그룹 해체이후 평소 우왁굳님의 방송을 챙겨봤던 릴파는 우왁굳이 버츄얼 아이돌을 모집하는 공지를 보고\r\n");
      out.write("				다시 한번 아이돌이 되고자 결심하였습니다. 현재는 이세돌에서 메인보컬로 좋은 활동을 하고 있습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"image-box\">\r\n");
      out.write("		<img src=\"resources/images/Lilpanew1.png\">\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("			function goMain(){\r\n");
      out.write("				location.href=\"");
      out.print( request.getContextPath());
      out.write("\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
