/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-12-01 23:10:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.uni.notice.model.vo.Notice;
import com.uni.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1669752492866L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1669926799245L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uni.member.model.vo.Member");
    _jspx_imports_classes.add("com.uni.notice.model.vo.Notice");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Notice> list = (ArrayList<Notice>) request.getAttribute("list");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>이세계 아이돌 팬 사이트</title>\r\n");
      out.write("<style>\r\n");
      out.write(".content{\r\n");
      out.write("	width:70%;\r\n");
      out.write("	height:800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#idx_top{\r\n");
      out.write("		width:100%; \r\n");
      out.write("		padding: 100px 0;\r\n");
      out.write("		background: url(resources/images/ise.jfif) no-repeat 50% 80% /cover;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#idx_top strong,\r\n");
      out.write("	#idx_top p{\r\n");
      out.write("		color:black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#idx_top strong{\r\n");
      out.write("		font-size:60px;\r\n");
      out.write("		letter-spacing: -2px;\r\n");
      out.write("	}\r\n");
      out.write("	#idx_top p span{\r\n");
      out.write("		color:purple;\r\n");
      out.write("	}\r\n");
      out.write("	#idx_top p{\r\n");
      out.write("		margin-top:20px;\r\n");
      out.write("		font-size:20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#idx_notice_wrap > div{\r\n");
      out.write("		width:90%;\r\n");
      out.write("		min-width:1000px;\r\n");
      out.write("		min-width:1200px;\r\n");
      out.write("		margin:0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#idx_notice_wrap{\r\n");
      out.write("		padding: 50px 0;\r\n");
      out.write("		background: gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice{\r\n");
      out.write("		width:500px;\r\n");
      out.write("		background:white;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .title{\r\n");
      out.write("		position:relative;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		border-bottom: 1px solid #aaa;\r\n");
      out.write("	}\r\n");
      out.write("	.idx_notice .title a{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		vertical-align:middle;\r\n");
      out.write("	}\r\n");
      out.write("	.idx_notice .name{\r\n");
      out.write("		font-size: 24px;\r\n");
      out.write("		font-weight: 600;\r\n");
      out.write("		letter-soacing: -2px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .more{\r\n");
      out.write("		position:absolute;\r\n");
      out.write("		top:25px;\r\n");
      out.write("		right:20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .more img{\r\n");
      out.write("		width: 24px;\r\n");
      out.write("		margin-left: 3px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .list{\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .list ul li{\r\n");
      out.write("		margin-top:10px;\r\n");
      out.write("		font-size:0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .list ul li:first-child{\r\n");
      out.write("		margin-top:0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .list a,\r\n");
      out.write("	.idx_notice .list span{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		vertical-align:middle;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.idx_notice .list a{\r\n");
      out.write("		width: 80%;\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("	.idx_notice .list span{\r\n");
      out.write("		width: 20%;\r\n");
      out.write("		text-align:right;\r\n");
      out.write("		font-size: 12px;\r\n");
      out.write("		color:gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.section input[id*=\"slide\"]{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write(".section .slidewrap{\r\n");
      out.write("	max-width:1500px;\r\n");
      out.write("	margin:0 auto;\r\n");
      out.write("	overflow:hidden;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist{\r\n");
      out.write("	white-space:nowrap;\r\n");
      out.write("	font-size:0;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist > li{\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	vertical-align:middle;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	transition:all .5s;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist > li > a {\r\n");
      out.write("	display:block;\r\n");
      out.write("	position:relative;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist > li > a img {\r\n");
      out.write("	width:100%;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist label{\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	z-index:10;\r\n");
      out.write("	top:50%;\r\n");
      out.write("	transform:translateY(-50%);\r\n");
      out.write("	padding:50px;\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist .left{\r\n");
      out.write("	left:30px;\r\n");
      out.write("	background:url('resources/images/left.png') center center / 100% no-repeat;	\r\n");
      out.write("}\r\n");
      out.write(".section .slidelist .right{\r\n");
      out.write("	right:30px;\r\n");
      out.write("	background:url('resources/images/right.png') center center / 100% no-repeat;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section [id=\"slide01\"]:checked ~ .slidewrap .slidelist > li {transform:translateX(0%);}\r\n");
      out.write(".section [id=\"slide02\"]:checked ~ .slidewrap .slidelist > li {transform:translateX(-100%);}\r\n");
      out.write(".section [id=\"slide03\"]:checked ~ .slidewrap .slidelist > li {transform:translateX(-200%);}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String msg = (String)session.getAttribute("msg");
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		background:url('");
      out.print(request.getContextPath() );
      out.write("/resources/images/2.jpg') no-repeat; \r\n");
      out.write("		background-position: 50% 50%;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-size: 50% 50%;\r\n");
      out.write("		background-color: black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#loginForm, #userInfo{float:right;}\r\n");
      out.write("	.btns button{border: 1px solid skyblue;\r\n");
      out.write("            background-color: rgba(0,0,0,0);\r\n");
      out.write("            color: skyblue;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("				  }\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#enrollBtn, #mypageBtn{\r\n");
      out.write("			border-top-right-radius: 5px;\r\n");
      out.write("            border-bottom-right-radius: 5px;    \r\n");
      out.write("            margin-left:-3px}\r\n");
      out.write("	#loginBtn, #logoutBtn{ \r\n");
      out.write("			border-top-left-radius: 5px;\r\n");
      out.write("            border-bottom-left-radius: 5px;\r\n");
      out.write("            margin-right:-4px;}\r\n");
      out.write("	#userInfo a{text-decoration:none;color:white;}\r\n");
      out.write("	\r\n");
      out.write("	.btns button:hover{border: 1px solid skyblue;\r\n");
      out.write("            background-color: skyblue;\r\n");
      out.write("            color: purple;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("				  }\r\n");
      out.write("	\r\n");
      out.write("	/* 메뉴영역 관련 스타일*/\r\n");
      out.write("	.navWrap{background-color:black; width:100%; height:50px}\r\n");
      out.write("	.navWrap>.nav{width:600px;margin:auto;}\r\n");
      out.write("	.menu{text-align:center;color:white;font-weight:bold;width:150px;height:50px;display:table-cell;font-size:20px;vertical-align:middle;}\r\n");
      out.write("	.menu:hover{background-color:rgb(250, 142, 174); text-shadow:5px 5px 5px rgb(0,0,0);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	.logo{\r\n");
      out.write("		float: lfet;\r\n");
      out.write("	}\r\n");
      out.write("	.logo img{\r\n");
      out.write("		height: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function loginValidate(){\r\n");
      out.write("		if($(\"#userId\").val().trim().length === 0){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if($(\"#userPwd\").val().trim().length === 0){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 class=\"logo\">\r\n");
      out.write("		<img src=\"resources/images/logo.png\" alt=\"로고\" >\r\n");
      out.write("	</h1>\r\n");
      out.write("	<h1 align=\"center\" style=\"color:white;\">이세계 아이돌</h1>\r\n");
      out.write("	<div class=\"loginArea\">\r\n");
      out.write("	");
 if( loginUser == null) { 
      out.write("\r\n");
      out.write("	<form id = \"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/loginMember.do\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th><label for = \"userId\" style=\"color:white;\">아이디</label></th>\r\n");
      out.write("					<td><input id=\"userId\" type=\"text\" name=\"userId\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th><label for = \"userPwd\" style=\"color:white;\">비밀번호</label></th>\r\n");
      out.write("					<td><input type=\"password\" id=\"userPwd\" type=\"text\" name=\"userPwd\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class =\"btns\" align=\"center\">\r\n");
      out.write("				\r\n");
      out.write("				<button id = \"loginBtn\" type=\"submit\">로그인</button>\r\n");
      out.write("			    <button id = \"enrollBtn\" type=\"button\" onclick=\"enrollPage();\">회원가입</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("	");
} else{ 
      out.write("\r\n");
      out.write("			<div id = \"userInfo\">\r\n");
      out.write("				<b style = \"color:white;\">");
      out.print(loginUser.getUserName() );
      out.write(" 님 </b> 의 방문을 환영합니다.\r\n");
      out.write("				<br><br>\r\n");
      out.write("				<div class =\"btns\" align=\"center\">\r\n");
      out.write("					<a href = \"");
      out.print(request.getContextPath() );
      out.write("/mypageMember.do\">마이페이지</a>\r\n");
      out.write("					<a href = \"");
      out.print(request.getContextPath() );
      out.write("/logoutMember.do\">로그아웃</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</div>	\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function enrollPage(){\r\n");
      out.write("			location.href =\"");
      out.print(request.getContextPath());
      out.write("/enrollFormMember.do\";\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<br clear=\"both\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"navWrap\">\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<div class=\"menu\" onclick=\"goMain();\">HOME</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goAbout();\">ABOUT</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goNotice();\">공지사항</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goBoard();\">게시판</div>\r\n");
      out.write("				<div class=\"menu\" onclick=\"goThumbnail();\">사진게시판</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("		function goMain(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function goAbout(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("/about.do\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function goNotice(){\r\n");
      out.write("			location.href=\"");
      out.print( request.getContextPath());
      out.write("/listNotice.do\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("			<div id=\"idx_top\">\r\n");
      out.write("				<strong>이세계아이돌</strong>\r\n");
      out.write("				<p>둘, 셋! 차원을 넘어! 안녕하세요, <span>이세계 아이돌</span>입니다!</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"idx_notice_wrap\">\r\n");
      out.write("			<div class=\"idx_notice\">\r\n");
      out.write("				<div class=\"title\">\r\n");
      out.write("					<a href=\"#\" class=\"name\">공지사항</a>\r\n");
      out.write("					<a href=\"#\" class=\"more\"><div onclick=\"goNotice();\"><img src=\"resources/images/more.png\" alt=\"더 보기\"></div></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"list\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">글 제목이 들어갑니다.</a>\r\n");
      out.write("							<span>2019-11-14</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">글 제목이 들어갑니다.</a>\r\n");
      out.write("							<span>2019-11-14</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">글 제목이 들어갑니다.</a>\r\n");
      out.write("							<span>2019-11-14</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">글 제목이 들어갑니다.</a>\r\n");
      out.write("							<span>2019-11-14</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">글 제목이 들어갑니다.</a>\r\n");
      out.write("							<span>2019-11-14</span>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<input type=\"radio\" name=\"slide\" id=\"slide01\" checked>\r\n");
      out.write("		<input type=\"radio\" name=\"slide\" id=\"slide02\">\r\n");
      out.write("		<input type=\"radio\" name=\"slide\" id=\"slide03\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"slidewrap\">\r\n");
      out.write("			<ul class=\"slidelist\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<a>\r\n");
      out.write("						<label for=\"slide03\" class=\"left\"></label>\r\n");
      out.write("						<img src=\"resources/images/01.jpg\">\r\n");
      out.write("						<label for=\"slide02\" class=\"right\"></label>\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a>\r\n");
      out.write("						<label for=\"slide01\" class=\"left\"></label>\r\n");
      out.write("						<img src=\"resources/images/02.jpg\">\r\n");
      out.write("						<label for=\"slide03\" class=\"right\"></label>\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a>\r\n");
      out.write("						<label for=\"slide02\" class=\"left\"></label>\r\n");
      out.write("						<img src=\"resources/images/03.jpg\">\r\n");
      out.write("						<label for=\"slide01\" class=\"right\"></label>\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* div{border:1px solid red;} */\r\n");
      out.write("    #footer{\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height:200px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("    }\r\n");
      out.write("    #footer>div{\r\n");
      out.write("    	width:100%;\r\n");
      out.write("    	padding-left:10%;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-1{\r\n");
      out.write("        height:20%;\r\n");
      out.write("        border-top:1px solid lightgray;\r\n");
      out.write("        border-bottom:1px solid lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2{\r\n");
      out.write("        height:80%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer-1 > a{\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin:10px;\r\n");
      out.write("        line-height: 40px;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #footer-2>p{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("    #p1{\r\n");
      out.write("    	color:white;\r\n");
      out.write("    }\r\n");
      out.write("    #p2{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("    }\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("	a:link{\r\n");
      out.write("		color:royalblue;\r\n");
      out.write("	    transition : 1s; /* 속성 변경할 때 효과의 속도 조절 */\r\n");
      out.write("	}\r\n");
      out.write("	a:visited {\r\n");
      out.write("		color:teal;\r\n");
      out.write("	}\r\n");
      out.write("	a:hover {\r\n");
      out.write("		color:purple;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	a:active{\r\n");
      out.write("		color:blue;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		text-decoration: none;	\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("        <div id=\"footer-1\">\r\n");
      out.write("            <a href=\"https://woowakgood.com/\">왁물원</a> | \r\n");
      out.write("            <a href=\"https://www.youtube.com/c/welshcorgimessi\">왁타버스</a> | \r\n");
      out.write("            <a href=\"https://github.com/ChoiYoonJong\">제작자:초이</a>  \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footer-2\">\r\n");
      out.write("            <p id=\"p1\">\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCroM00J2ahCN6k-0-oAiDxg\">아이네</a> : 1994년|158cm|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/c/%EC%A7%95%EB%B2%84%EA%B1%B0\">징버거</a> : 1995년10월08일|161.9cm|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UC-oCJP9t47v7-DmsnmXV38Q\">릴파</a> : 1996년03월09일|164cm|O형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/c/%EC%A3%BC%EB%A5%B4%EB%A5%B4\">주르르</a> : 1997년06월10일|161.9cm|O형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCV9WL7sW6_KjanYkUUaIDfQ\">고세구</a> : 1998년|300m|B형 <br>\r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCs6EwgxKLY9GG4QNUrP5hoQ\">비챤</a> : 2000년01월16일|160cm|B형 \r\n");
      out.write("                \r\n");
      out.write("            </p>  \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
